typography_spectrum: 0.5670665968209505
color:
  brandStrength: 0.2874414708930999
  lightness: 0.515475666616112
  saturation: 0.04666826291941106
  rhythmicContrast: 0.44644839596003294
  brandColors:
    - '#DBD5C5'
    - '#A49E92'
    - '#877F72'
    - '#FFFFFA'
    - '#716952'
layout_spectrum: 0.5552736329846084
author:
  name: Casper
  email: casper@ibarem.com
  url: www.ibarem.com
name: IBAREM - dream houses in spain
navigation:
  - name: Welcome
    id: b4d79cc3-71e2-405e-9d0d-7b800625db65
    type: content
title: Your building partner in Spain
description: We Design & Develop Your New Dream House
