typography_spectrum: 0.14956812490709126
color:
  brandStrength: 0.4652578290551901
  lightness: 0.788574893726036
  saturation: 0.12116103409789503
  rhythmicContrast: 0.6377405268140137
  brandColors:
    - '#EEEEEE'
    - '#A4A4A4'
    - '#79634C'
    - '#2E251C'
    - '#4B9ACB'
layout_spectrum: 0.5521859545260668
author:
  name: Casper
  email: casper@ibarem.com
  url: www.ibarem.com
name: IBAREM - dream houses in spain
navigation:
  - name: Welcome
    id: b4d79cc3-71e2-405e-9d0d-7b800625db65
    type: content
title: Your building partner in Spain
description: We Design & Develop Your New Dream House
